theme: jekyll-theme-minimal
title: <p align="center">PHAT Nguyen</p>
logo: "/assets/img/logo.png?raw=true"
description: Embedded Firmware/Software
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  
  <br>
  <i style="font-size:18px;" class="fa fa-map-marker"> Vietnam</i>
  <br>
  
  <br>
  <i style="font-size:18px;color:#4485e0" class="fa fa-envelope"></i>
  <a href="mailto:phat.nt@hotmail.com">Email</a>
  
  <br>
  <i style="font-size:18px" class="fa fa-github"></i>
  <a href="https://github.com/pnt325">Github</a>
  
  <br>
  <i style="font-size:18px;color:#0077b5" class="fa fa-linkedin"></i>
  <a href="https://www.linkedin.com/in/phatnt/">Linkedin</a>
  
  <br>
  <i style="font-size:18px;color:red" class="fa fa-youtube"></i>
  <a href="https://www.youtube.com/c/PhatNguyenDIY">Youtube</a>

relative_links:
  enabled:     true
  collections: false
