theme: jekyll-theme-minimal
title: <p align="center">PHAT Nguyen</p>
logo: "/assets/img/logo.png?raw=true"
description: Embedded Firmware/Software
  <br>
  <i style="font-size:18px;" class="fa fa-envelope"></i>
  <a href="mailto:phat.nt@hotmail.com">Email</a>
  <br>
  <i style="font-size:18px" class="fa fa-github"></i>
  <a href="https://github.com/pnt325">Github</a>
  <br>
  <i style="font-size:18px" class="fa fa-linkedin"></i>
  <a href="https://www.linkedin.com/in/phatnt/">Linkedin</a>
  <br>
  <i style="font-size:18px" class="fa fa-youtube"></i>
  <a href="https://www.linkedin.com/in/phatnt/">Youtube</a>

relative_links:
  enabled:     true
  collections: false
