theme: jekyll-theme-minimal
title: PHAT Nguyen Homepage
description: This is page where I share experience and project.

search: true
minimal_mistakes_skin: true

author:
  name: "Phat Nguyen"
  avartar: "/assets/img/logo.jpg"
  bio: "Embedded firmware/software"
