theme: jekyll-theme-minimal
title: PHAT Nguyen
logo: /assets/img/logo.jpg
description: Embedded Firmware/Software

author:
  name: Phat Nguyen
  email: phat.nt@hotmail.com

social_links:
  linkedin: phatnt

relative_links:
  enabled:     true
  collections: false
